# MoveIt uses this configuration for controller management
trajectory_execution:
  moveit_manage_controllers: Flase
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_execution.execution_duration_monitoring: False,

